In [2]:
from numpy import random
print(random.randint(1,100))
print(random.rand())

56
0.29777711176466426


In [3]:
#creating n - dimensional array with random elemnents
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[ 3 35 92]
[[55 96 57 23]
 [85 49 11 81]
 [70 50 37 81]]
[[[45  5]
  [32 18]
  [71 62]
  [53 73]]

 [[34 78]
  [28 54]
  [77 10]
  [89 59]]

 [[83 53]
  [72 99]
  [63 13]
  [46 77]]]


In [4]:
#creating n-dimensional array with random integer
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.4754789555900646
[0.7652302  0.87054452 0.53493512]
[[0.46208084 0.54008488 0.41958085]
 [0.19335652 0.77215407 0.23882362]]


In [7]:
a = random.randint(100,size = (3,2)).ravel()
a


array([90, 44, 20, 78,  3,  6])

In [8]:
# single element will be selected
random.choice(a)

3

In [12]:
#for generating an array eith the given shape and elements from given set
random.choice([1,2,3,4,5],size=(4,4))

array([[5, 3, 5, 5],
       [4, 2, 1, 3],
       [2, 3, 4, 5],
       [1, 4, 3, 3]])

### Pandas :
1. Data Manipulation , analysis and cleaning
2. Tabular Data ,orderd and unordered,unlabelled

### creating a Dataframe
1. using two dictionaries
2. simple dictionary --->Data frame

In [1]:
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 = {'a':5,'b':6,'c':7,'d':8,'e':9}
data = {"first":dict1,"second":dict2}
df = pd.DataFrame(data,dtype=np.int32)
df

first  second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [4]:
#simple dictionary ---> dataframe
d1 = {"name":["pranathi","manasa","shivani","ujwala"],"address":["sdpt","ap","sdpt","hyd"]}
df1 = pd.DataFrame(d1)
df1

name address
0  pranathi    sdpt
1    manasa      ap
2   shivani    sdpt
3    ujwala     hyd

In [7]:
#using series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.34,45.3,45.5,36.5,10.9,5.06,3.6,7.5,40.60])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data  = {"Series1":s1,"Series2":s2,"Series3":s3}
df3 = pd.DataFrame(data)
df3

Series1  Series2 Series3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c
3        4    45.50       d
4        5    36.50       e
5        6    10.90       f
6        7     5.06       g
7        8     3.60       h
8        9     7.50       i
9       10    40.60       j

### selcting data from data frame
1. loc
2. iloc

In [14]:
#df3["Series3"]--->single column
df3[["Series3","Series2"]] # multiple colums

Series3  Series2
0       a    12.23
1       b    23.34
2       c    45.30
3       d    45.50
4       e    36.50
5       f    10.90
6       g     5.06
7       h     3.60
8       i     7.50
9       j    40.60

In [15]:
df3.loc[:,"Series1"] #[row position : column position]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: Series1, dtype: int64

In [18]:
#multiple columns
df3.loc[0:5:,["Series1","Series2"]]#[rows,colum]

Series1  Series2
0        1    12.23
1        2    23.34
2        3    45.30
3        4    45.50
4        5    36.50
5        6    10.90

In [24]:
df3.iloc[1:4,1:2]#df3.iloc[start row number:stop(no of rows),start colum:stp colum]

Series2
1    23.34
2    45.30
3    45.50

### Retriving  information from data set

In [25]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
Series1    10 non-null int64
Series2    10 non-null float64
Series3    10 non-null object
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [27]:
df3.shape

(10, 3)

In [29]:
df3.columns

Index(['Series1', 'Series2', 'Series3'], dtype='object')

In [30]:
df3.index

RangeIndex(start=0, stop=10, step=1)

### Viewing data
1. head()
2. tail()
3. sample()


In [33]:
# first half
df3.head()

Series1  Series2 Series3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c

In [34]:
df3.head(3)

Series1  Series2 Series3
0        1    12.23       a
1        2    23.34       b
2        3    45.30       c

In [35]:
df3.tail()

Series1  Series2 Series3
5        6    10.90       f
6        7     5.06       g
7        8     3.60       h
8        9     7.50       i
9       10    40.60       j

In [37]:
df3.sample() #random

Series1  Series2 Series3
2        3     45.3       c

In [39]:
df3.sample(3)

Series1  Series2 Series3
7        8      3.6       h
4        5     36.5       e
3        4     45.5       d

In [44]:
df3.describe()

Series1    Series2
count  10.00000  10.000000
mean    5.50000  23.053000
std     3.02765  17.309259
min     1.00000   3.600000
25%     3.25000   8.350000
50%     5.50000  17.785000
75%     7.75000  39.575000
max    10.00000  45.500000

In [46]:
df3 = df3.rename(columns={"Series1":"First","Series2":"Second","Series3":"Third"})
df3

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   45.30     c
3      4   45.50     d
4      5   36.50     e
5      6   10.90     f
6      7    5.06     g
7      8    3.60     h
8      9    7.50     i
9     10   40.60     j

In [53]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
